Repository kubernetes-sigs/release-sdk, pull requests merged in 2021-11, with the labels that each got.

#11 github: Detect secondary rate limit
  github/internal/retry.go
  github/internal/retry_test.go
Labels: kind/bug, kind/flake, kind/failing-test, size/S, cncf-cla: yes, sig/release, lgtm, approved, priority/important-soon

#12 LICENSE: Init Apache 2.0 license
  LICENSE
Labels: priority/critical-urgent, cncf-cla: yes, sig/release, lgtm, size/L, approved

#13 github: Add forking functionality from `krel release-notes`
  github/fork.go
Labels: cncf-cla: yes, sig/release, lgtm, size/L, approved
