Repository kubernetes-sigs/release-sdk, pull requests merged in 2021-10, with the labels that each got.

#7 OWNERS: Update to match the current SIG Release roles
  OWNERS
  OWNERS_ALIASES
Labels: size/S, cncf-cla: yes, sig/release, lgtm, approved

#9 Bump go-github to v39
  github/github.go
  github/github_test.go
  github/githubfakes/fake_client.go
  github/internal/retry.go
  github/internal/retry_test.go
  github/record.go
  github/replay.go
  go.mod
  go.sum
Labels: size/M, cncf-cla: yes, sig/release, lgtm, approved

#8 Add support for GitHub rate limit error
  github/internal/retry.go
  github/internal/retry_test.go
Labels: size/M, cncf-cla: yes, sig/release, lgtm, approved

#10 Check for negative wait durations
  github/internal/retry.go
Labels: cncf-cla: yes, sig/release, lgtm, size/XS, approved
