Repository kubernetes-sigs/release-sdk, pull requests merged in 2022-12, with the labels that each got.

#136 block commands that can run malicious injection
  git/git.go
Labels: kind/bug, cncf-cla: yes, sig/release, lgtm, size/XS, approved

#138 Make `git.DefaultGitUser` and `git.DefaultGitEmail` public
  git/git.go
Labels: kind/feature, size/S, cncf-cla: yes, sig/release, lgtm, approved

#139 Add `ListIssues` GitHub API
  github/github.go
  github/github_test.go
  github/githubfakes/fake_client.go
  github/record.go
  github/replay.go
Labels: kind/feature, cncf-cla: yes, sig/release, lgtm, size/L, approved

#141 Fix `RemoteTags()` method
  git/git.go
Labels: kind/bug, kind/regression, cncf-cla: yes, sig/release, lgtm, size/XS, approved
