Repository kubernetes-sigs/release-sdk, pull requests merged in 2022-06, with the labels that each got.

#74 Update `go-github` to v45
  github/github.go
  github/github_test.go
  github/githubfakes/fake_client.go
  github/internal/retry.go
  github/internal/retry_test.go
  github/record.go
  github/replay.go
  go.mod
  go.sum
Labels: size/S, kind/cleanup, cncf-cla: yes, sig/release, lgtm, approved

#73 Pin `go-containerregistry` and `release-utils`
  go.mod
  go.sum
Labels: size/M, kind/cleanup, cncf-cla: yes, sig/release, lgtm, approved

#75 Revert httpcache integration
  github/github.go
  go.mod
  go.sum
Labels: kind/bug, size/S, cncf-cla: yes, sig/release, lgtm, approved

#77 Bump sigstore/cosign to HEAD
  go.mod
  go.sum
Labels: kind/cleanup, cncf-cla: yes, sig/release, lgtm, size/L, approved
