Repository kubernetes-sigs/release-sdk, pull requests merged in 2023-01, with the labels that each got.

#147 go.mod: Update `github.com/google/go-github` to v48.2.0
  github/github.go
  github/github_test.go
  github/githubfakes/fake_client.go
  github/internal/retry.go
  github/internal/retry_test.go
  github/record.go
  github/replay.go
  go.mod
  go.sum
Labels: size/S, kind/cleanup, cncf-cla: yes, sig/release, lgtm, approved

#148 github: Add `ListComments` method
  github/github.go
  github/github_test.go
  github/githubfakes/fake_client.go
  github/record.go
  github/replay.go
Labels: kind/feature, cncf-cla: yes, sig/release, lgtm, size/L, approved

#143 Offboard Release Manager Associates
  OWNERS_ALIASES
Labels: size/S, kind/cleanup, cncf-cla: yes, sig/release, lgtm, approved

#152 Allow `main` to be a release branch
  regex/regex.go
Labels: kind/feature, cncf-cla: yes, sig/release, lgtm, size/XS, approved
