Repository kubernetes-sigs/release-sdk, pull requests merged in 2023-10, with the labels that each got.

#254 obs: add library functions - 02
  obs/project.go
Labels: size/M, ok-to-test, cncf-cla: yes, sig/release, lgtm, approved

#266 obs: fix null pointer exception when xml data is null
  obs/project.go
Labels: cncf-cla: yes, sig/release, lgtm, size/XS, approved

#268 bump release-utils and github.com/google/go-github
  github/github.go
  github/github_test.go
  github/githubfakes/fake_client.go
  github/internal/retry.go
  github/internal/retry_test.go
  github/record.go
  github/replay.go
  go.mod
  go.sum
  magefile.go
Labels: kind/feature, size/S, kind/cleanup, cncf-cla: yes, sig/release, lgtm, approved
