Repository kubernetes-sigs/release-sdk, pull requests merged in 2023-12, with the labels that each got.

#283 Shallow clone variants
  git/git.go
Labels: kind/feature, cncf-cla: yes, sig/release, lgtm, size/L, approved

#289 add ConfigureGlobalCustomUserAndEmail function
  git/git.go
Labels: kind/feature, size/S, cncf-cla: yes, sig/release, lgtm, approved

#288 Add additional method to update GitHub releases with more flexible opts
  github/github.go
  github/github_test.go
  go.mod
Labels: kind/feature, ok-to-test, cncf-cla: yes, sig/release, lgtm, size/L, approved

#291 Publish the marker inside the fast folder
  object/gcs.go
  object/gcs_test.go
  object/objectfakes/fake_store.go
  object/store.go
Labels: kind/bug, size/M, cncf-cla: yes, sig/release, lgtm, approved

#292 Update preparefork to accept ssh/http option and add new function to push with options
  git/git.go
  git/gitfakes/fake_repository.go
  github/fork.go
  test/integration/git_test.go
Labels: kind/feature, size/M, cncf-cla: yes, sig/release, lgtm, approved

#294 add options to preparefork to when you need to configure special things
  git/git.go
  git/git_test.go
  github/fork.go
  test/integration/git_test.go
Labels: kind/feature, size/S, cncf-cla: yes, sig/release, lgtm, approved

#295 add option to not update the repo
  git/git.go
  git/git_test.go
  github/fork.go
  test/integration/git_test.go
Labels: kind/feature, size/M, cncf-cla: yes, sig/release, lgtm, approved
