Repository kubernetes-sigs/release-sdk, pull requests merged in 2023-09, with the labels that each got.

#246 obs: add initial Project types
  .gitignore
  obs/project.go
Labels: size/M, ok-to-test, cncf-cla: yes, sig/release, lgtm, approved

#252 update go-github to v55
  github/github.go
  github/github_test.go
  github/githubfakes/fake_client.go
  github/internal/retry.go
  github/internal/retry_test.go
  github/record.go
  github/replay.go
  go.mod
  go.sum
Labels: kind/feature, size/M, kind/cleanup, cncf-cla: yes, sig/release, lgtm, approved

#251 obs: add library functions - 01
  obs/error.go
  obs/project.go
Labels: ok-to-test, cncf-cla: yes, sig/release, lgtm, size/L, approved
