Repository kubernetes-sigs/release-sdk, pull requests merged in 2024-04, with the labels that each got.

#331 fix e2e tests
  .github/workflows/e2e.yml
  dependencies.yaml
  sign/sign.go
  test/e2e/sign_test.go
Labels: kind/bug, size/M, cncf-cla: yes, sig/release, lgtm, approved

#333 run only on kubernetes-sigs/release-sdk repo
  .github/workflows/e2e.yml
Labels: kind/cleanup, cncf-cla: yes, sig/release, lgtm, size/XS, approved

#336 add rate limit api check
  github/github.go
  github/github_test.go
  github/githubfakes/fake_client.go
  github/record.go
  github/replay.go
Labels: kind/feature, cncf-cla: yes, sig/release, lgtm, size/L, approved

#338 fix NewWithTokenWithClient so it preserves the original http client t…
  github/github.go
Labels: kind/bug, ok-to-test, size/S, cncf-cla: yes, sig/release, lgtm, approved

#344 Enable and fix `perfsprint` linter
  .golangci.yml
  git/git.go
  git/git_test.go
  github/internal/retry_test.go
  sign/sign.go
Labels: size/M, kind/cleanup, cncf-cla: yes, sig/release, lgtm, approved
