Repository kubernetes-sigs/release-sdk, pull requests merged in 2025-01, with the labels that each got.

#405 update go-git
  go.mod
  go.sum
  test/integration/git_test.go
Labels: kind/cleanup, cncf-cla: yes, sig/release, lgtm, size/L, approved

#407 fix TestCommitSuccess test
  test/integration/git_test.go
Labels: kind/bug, size/M, cncf-cla: yes, sig/release, lgtm, approved

#408 update TestCommitSuccess test
  test/integration/git_test.go
Labels: kind/cleanup, cncf-cla: yes, sig/release, lgtm, size/XS, approved

#418 Update golangci-lint config and fix reports
  .golangci.yml
  gcli/gcli.go
  git/describe.go
  git/git.go
  git/git_test.go
  github/fork.go
  github/github.go
  github/github_test.go
  github/internal/retry.go
  github/internal/retry_test.go
  github/record.go
  github/replay.go
  go.mod
  go.sum
  object/gcs.go
  obs/packages.go
  obs/project.go
  osc/osc.go
  osc/osc_test.go
  sign/impl.go
  sign/options.go
  sign/sign.go
  sign/sign_test.go
  test/integration/container_registry.go
  test/integration/git_test.go
  test/integration/sign_test.go
Labels: kind/cleanup, size/XL, cncf-cla: yes, sig/release, lgtm, approved
